import type { Metadata } from "next";
import Link from "next/link";
import "../../app/globals.css";

export const metadata: Metadata = {
  title: "e-Stat API Viewer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Link href="/" className="header-home-link">
          e-Stat API Viewer
        </Link>
        {children}
      </body>
    </html>
  );
}
